version: 2.0

jobs:
  Py2:
    machine: true
    steps:
      - checkout
      - run: docker build -t ubuntu-py2 -f Dockerfile --build-arg PYTHON_VERSION=2.7 .
      - run: docker images && docker run -i -t ubuntu-py2 python -c "import sys, cv2 ; print(sys.version) ; print(cv2.__version__)"

  Py3:
    machine: true
    steps:
      - checkout
      - run: docker build -t ubuntu-py3 -f Dockerfile --build-arg PYTHON_VERSION=3.6 .
      - run: docker images && docker run -i -t ubuntu-py3 python -c "import sys, cv2 ; print(sys.version) ; print(cv2.__version__)"

  Py2-CUDA:
    machine: true
    steps:
      - checkout
      - run:
          command: docker build -t ubuntu-cuda-py2 -f Dockerfile.cuda --build-arg PYTHON_VERSION=2.7 .
          no_output_timeout: 60m
      - run: docker images && docker run -i -t ubuntu-cuda-py2 python -c "import sys, cv2 ; print(sys.version) ; print(cv2.__version__)"

  Py3-CUDA:
    machine: true
    steps:
      - checkout
      - run:
          command: docker build -t ubuntu-cuda-py3 -f Dockerfile.cuda --build-arg PYTHON_VERSION=3.6 .
          no_output_timeout: 60m
      - run: docker images && docker run -i -t ubuntu-cuda-py3 python -c "import sys, cv2 ; print(sys.version) ; print(cv2.__version__)"

workflows:
  version: 2
  build:
    jobs:
      - Py2
      - Py3
      - Py2-CUDA
      - Py3-CUDA
